[tools]
aws-cli = "latest"
delta = "latest"
fzf = "latest"
github-cli = "latest"
go = "latest"
jj = "latest"
jq = "latest"
lazygit = "latest"
lua = "latest"
neovim = "latest"
node = "22"
python = "latest"
ripgrep = "latest"
ruby = "latest"
rust = "latest"
tmux = "latest"
zig = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
